# Form implementation generated from reading ui file 'ui_add.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Add(object):
    def setupUi(self, Add):
        Add.setObjectName("Add")
        Add.resize(800, 600)
        self.gridLayout_5 = QtWidgets.QGridLayout(Add)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.PushButton_intersection = PushButton(parent=Add)
        self.PushButton_intersection.setObjectName("PushButton_intersection")
        self.gridLayout_2.addWidget(self.PushButton_intersection, 2, 0, 1, 1)
        self.PushButton_point_on_line = PushButton(parent=Add)
        self.PushButton_point_on_line.setObjectName("PushButton_point_on_line")
        self.gridLayout_2.addWidget(self.PushButton_point_on_line, 3, 0, 1, 1)
        self.PushButton_point = PushButton(parent=Add)
        self.PushButton_point.setObjectName("PushButton_point")
        self.gridLayout_2.addWidget(self.PushButton_point, 1, 0, 1, 1)
        self.CardWidget = CardWidget(parent=Add)
        self.CardWidget.setObjectName("CardWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.CardWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.ListWidget_points = ListWidget(parent=self.CardWidget)
        self.ListWidget_points.setObjectName("ListWidget_points")
        self.gridLayout.addWidget(self.ListWidget_points, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.CardWidget, 5, 0, 1, 1)
        self.TitleLabel = TitleLabel(parent=Add)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout_2.addWidget(self.TitleLabel, 0, 0, 1, 1)
        self.SubtitleLabel = SubtitleLabel(parent=Add)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.gridLayout_2.addWidget(self.SubtitleLabel, 4, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.TitleLabel_2 = TitleLabel(parent=Add)
        self.TitleLabel_2.setObjectName("TitleLabel_2")
        self.gridLayout_4.addWidget(self.TitleLabel_2, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.PushButton_parallel = PushButton(parent=Add)
        self.PushButton_parallel.setObjectName("PushButton_parallel")
        self.gridLayout_4.addWidget(self.PushButton_parallel, 1, 0, 1, 3)
        self.PushButton_vertical = PushButton(parent=Add)
        self.PushButton_vertical.setObjectName("PushButton_vertical")
        self.gridLayout_4.addWidget(self.PushButton_vertical, 2, 0, 1, 3)
        self.PushButton_eq = PushButton(parent=Add)
        self.PushButton_eq.setObjectName("PushButton_eq")
        self.gridLayout_4.addWidget(self.PushButton_eq, 3, 0, 1, 3)
        self.SubtitleLabel_2 = SubtitleLabel(parent=Add)
        self.SubtitleLabel_2.setObjectName("SubtitleLabel_2")
        self.gridLayout_4.addWidget(self.SubtitleLabel_2, 4, 0, 1, 3)
        self.CardWidget_2 = CardWidget(parent=Add)
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.CardWidget_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ListWidget_conditions = ListWidget(parent=self.CardWidget_2)
        self.ListWidget_conditions.setObjectName("ListWidget_conditions")
        self.gridLayout_3.addWidget(self.ListWidget_conditions, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.CardWidget_2, 5, 0, 1, 3)
        self.CheckBox_pre_simplify = CheckBox(parent=Add)
        self.CheckBox_pre_simplify.setChecked(True)
        self.CheckBox_pre_simplify.setObjectName("CheckBox_pre_simplify")
        self.gridLayout_4.addWidget(self.CheckBox_pre_simplify, 0, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 1, 1, 1)

        self.retranslateUi(Add)
        QtCore.QMetaObject.connectSlotsByName(Add)

    def retranslateUi(self, Add):
        _translate = QtCore.QCoreApplication.translate
        Add.setWindowTitle(_translate("Add", "Form"))
        self.PushButton_intersection.setText(_translate("Add", "添加交点"))
        self.PushButton_point_on_line.setText(_translate("Add", "添加线上的点"))
        self.PushButton_point.setText(_translate("Add", "添加点"))
        self.TitleLabel.setText(_translate("Add", "创建点"))
        self.SubtitleLabel.setText(_translate("Add", "已有的点："))
        self.TitleLabel_2.setText(_translate("Add", "条件"))
        self.PushButton_parallel.setText(_translate("Add", "平行"))
        self.PushButton_vertical.setText(_translate("Add", "垂直"))
        self.PushButton_eq.setText(_translate("Add", "等式"))
        self.SubtitleLabel_2.setText(_translate("Add", "已有的条件（方程）："))
        self.CheckBox_pre_simplify.setText(_translate("Add", "预化简"))
from qfluentwidgets import CardWidget, CheckBox, ListWidget, PushButton, SubtitleLabel, TitleLabel
